force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <label>Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post__c/fields/AuthorId__c.field-meta.xml
<CustomField>
    <fullName>AuthorId__c</fullName>
    <label>AuthorId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PostTriggerHandler.cls
public class PostTriggerHandler {
    @future (callout=true)
    public static void createPost (String newListStr) {
        List<Post__c> newList = (List<Post__c>) JSON.deserialize(newListStr, List<Post__c>.class);
        List<PostController.PostWrapper> postWrList = new List<PostController.PostWrapper>();
        for (Post__c post : newList) {
            postWrList.add (new PostController.PostWrapper (Integer.valueOf(post.AuthorId__c), post.Title__c, post.Body__c));
        }
        String body = JSON.serialize(postWrList);
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json; charset=UTF-8');
        request.setBody (body);
        request.setEndpoint('https://jsonplaceholder.typicode.com/posts');
        HttpResponse response = http.send(request);
        system.debug(response.getBody());
    }
}