force-app/main/default/objects/Good1__c/Good1__c.object-meta.xml
<CustomObject>
    <label>Good1</label>
    <nameField>
        <label>Good! Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goods1</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Good1__c/fields/OrderGood__c.field-meta.xml
<CustomField>
    <fullName>OrderGood__c</fullName>
    <label>OrderGood</label>
    <referenceTo>OrderGood__c</referenceTo>
    <relationshipLabel>Goods1</relationshipLabel>
    <relationshipName>Goods1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderGood__c/OrderGood__c.object-meta.xml
<CustomObject>
    <label>OrderGood</label>
    <nameField>
        <label>OrderGood Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderGoods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderGood__c/fields/Name_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Name_Supplier__c</fullName>
    <label>Name Supplier</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Supplier__c/fields/Good1__c.field-meta.xml
<CustomField>
    <fullName>Good1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Good1</label>
    <referenceTo>Good1__c</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MyBatchClass.cls
public class MyBatchClass implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id FROM OrderGood__c]);
        // collect the batches of records or objects to be passed to execute
    }
    public void execute(Database.BatchableContext bc, List<OrderGood__c> records){
        Set<id> IdSet = new Set<id>();
              for (OrderGood__c orderGood : records){
            IdSet.add(orderGood.id);
        }
        list<Supplier__c> supplierList = [SELECT Name, Good1__r.OrderGood__c FROM Supplier__c WHERE Good1__r.OrderGood__c IN: IdSet AND Active__c = TRUE]; //Квери чайлдов
        Map<Id, list<Supplier__c>> mapSupplier = new Map<Id, list<Supplier__c>>();
        for (Supplier__c sup : supplierList) {
            if (mapSupplier.get(sup.Good1__r.OrderGood__c) != null) {
                list<Supplier__c> supList = mapSupplier.get(sup.Good1__r.OrderGood__c);
                supList.add(sup);
                mapSupplier.put(sup.Good1__r.OrderGood__c,supList);
            } else {
                mapSupplier.put(sup.Good1__r.OrderGood__c, new List<Supplier__c> {sup}); //мапа хранит значения каждого деда
            }
        }
        List<OrderGood__c> orderGoodListToUpdate = new List<OrderGood__c> ();
        for (Id key : mapSupplier.keySet()){
            list<Supplier__c> supList = mapSupplier.get(key);
            String nameString = '';
            for (Supplier__c sup : supList) {
                nameString += ' ' + sup.Name;
            }
            orderGoodListToUpdate.add(new OrderGood__c(Id = key, Name_Supplier__c = nameString));
        }
        update orderGoodListToUpdate;
    }
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}