force-app/main/default/objects/Good1__c/Good1__c.object-meta.xml
<CustomObject>
    <label>Good1</label>
    <nameField>
        <label>Good! Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goods1</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Good1__c/fields/OrderGood__c.field-meta.xml
<CustomField>
    <fullName>OrderGood__c</fullName>
    <label>OrderGood</label>
    <referenceTo>OrderGood__c</referenceTo>
    <relationshipLabel>Goods1</relationshipLabel>
    <relationshipName>Goods1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderGood__c/OrderGood__c.object-meta.xml
<CustomObject>
    <label>OrderGood</label>
    <nameField>
        <label>OrderGood Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderGoods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderGood__c/fields/Name_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Name_Supplier__c</fullName>
    <label>Name Supplier</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Supplier__c/fields/Good1__c.field-meta.xml
<CustomField>
    <fullName>Good1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Good1</label>
    <referenceTo>Good1__c</referenceTo>
    <relationshipLabel>Suppliers</relationshipLabel>
    <relationshipName>Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier__c/fields/Last_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Last_Delivery__c</fullName>
    <label>Last Delivery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SepplierTriggerHendler.cls
public class SepplierTriggerHendler {
    @future
    public static void updateOlderAccounts(String newListStr, String oldMapStr) {
        List<Supplier__c> newList =(List<Supplier__c>) JSON.deserialize(newListStr, List<Supplier__c>.class);
        Map<Id,Supplier__c> oldMap =(Map<Id,Supplier__c>) JSON.deserialize(oldMapStr, Map<Id,Supplier__c>.class);
        Set<id> IdSet = new Set<id>();
        if (newList != null) {
          for (Supplier__c newRecord : newList)
            {
                if (oldMap == null || newRecord.Active__c != oldMap.get(newRecord.Id).Active__c) {  //Отсеял поля Актив которые не поменялись
                    IdSet.add(newRecord.Good1__c);}
             }  
        } else {
            for (Supplier__c oldRecord : oldMap.values())
            {
                IdSet.add(oldRecord.Good1__c);
             }  
        }
        List<Good1__c> goodList = [SELECT OrderGood__c FROM Good1__c WHERE Id IN: IdSet];
        Set<Id> orderGoodIdSet = new Set<Id>();
        for (Good1__c good : goodList){
            orderGoodIdSet.add(good.OrderGood__c);
        }
        list<Supplier__c> supplierList = [SELECT Name, Good1__r.OrderGood__c FROM Supplier__c WHERE Good1__r.OrderGood__c IN: orderGoodIdSet AND Active__c = TRUE]; //Квери чайлдов
        Map<Id, String> orderGoodNameMap = new Map<Id, String>();
        	for (Supplier__c sup : supplierList) {
            	orderGoodNameMap.put(sup.Good1__r.OrderGood__c, orderGoodNameMap.get(sup.Good1__r.OrderGood__c) + ' ' + sup.Name);
        }
        List<OrderGood__c> orderGoodListToUpdate = new List<OrderGood__c> ();
        for (Id key : orderGoodNameMap.keySet()){
            
            orderGoodListToUpdate.add(new OrderGood__c(Id = key, Name_Supplier__c = orderGoodNameMap.get(key).remove('null')));
        }
        update orderGoodListToUpdate;
    }
    @future
    public static void updateActivity(String newListStr,String oldMapStr) {
        List<Supplier__c> newList =(List<Supplier__c>) JSON.deserialize(newListStr, List<Supplier__c>.class);
        Map<id, Supplier__c> oldMap =(Map<id, Supplier__c>) JSON.deserialize(oldMapStr, Map<id, Supplier__c>.class);
        for (Supplier__c newRecord : newList) {
            if (newRecord.Last_Delivery__c != null && newRecord.Last_Delivery__c != oldMap.get(newRecord.Id).Last_Delivery__c) {
                if (newRecord.Last_Delivery__c.addDays(30) < Date.today()){
                    newRecord.Active__c = False;
                } else {
                    newRecord.Active__c = true;
                }
            } else if (newRecord.Last_Delivery__c == null) {
                newRecord.Active__c = False;
            }
        }
    }
    public static void upsertPost (List<Supplier__c> newList, Map<id, Supplier__c> oldMap) {
        Boolean createPost = false;
        for (Supplier__c newRecord : newList) {
            if (newRecord.Last_Delivery__c !=null && (oldMap == null || newRecord.Last_Delivery__c != oldMap.get(newRecord.Id).Last_Delivery__c)) {
                createPost = true;
            }
        }
        if (createPost) {
            ID jobID = System.enqueueJob(new PostController());
        }
    }
        
}